name: UltraCommand
version: 1.0.0
authors: [rmellis, Kier Davis]
main: com.kierdavis.ultracommand.UltraCommand

commands:
    uc:
        description: UltraCommand alias
    ultracommand:
        description: UltraCommand main command

permissions:
    ultracommand.configure:
        description: Gives access to the /uc and /ultracommand commands.
        default: op
    
    ultracommand.commands.*:
        description: Gives access to all custom commands defined with this plugin.
        default: op
    
    ultracommand.commands.<name>:
        description: Gives access to the custom command named <name>.
