name: UltraCommand
version: 1.0.1
authors: [rmellis, Kier Davis]
main: com.kierdavis.ultracommand.UltraCommand
description: UltraCommand allows minecraft server admins to define unlimited custom commands.
load: STARTUP
website: https://github.com/rmellis/UltraCommand
loadbefore: [Essentials, CMI]
commands:
    uc:
        description: UltraCommand
    ultracommand:
        description: UltraCommand
permissions:
    ultracommand.configure:
        description: Gives access to the /uc and /ultracommand commands.
        default: op
    ultracommand.commands.*:
        description: Gives access to all custom commands defined with this plugin.
        default: op
    ultracommand.commands.<name>:
        description: Gives access to the custom command named <name>.
